config/routes.rb
Rails.application.routes.draw do
  resources :proyects
  root 'proyects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    enum info: [:Propuesta, :En_progreso, :Terminado]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: %i[ show edit update destroy ]

  # GET /proyects or /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1 or /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects or /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: "Proyect was successfully created." }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1 or /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: "Proyect was successfully updated." }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1 or /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: "Proyect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyect_params
      params.require(:proyect).permit(:name, :description, :start, :finish,:info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proyects/_form.html.erb
<%= form_with(model: proyect) do |form| %>
  <% if proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
        <% proyect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.date_select :start %>
  </div>

  <div class="field">
    <%= form.label :finish %>
    <%= form.date_select :finish %>
  </div>

  <div class="field">
    <%= form.label 'Status'%>
    <%= form.select :info, Proyect.infos.keys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.name %></td>
        <td><%= proyect.description %></td>
        <td><%= proyect.start %></td>
        <td><%= proyect.finish %></td>
        <td><%= proyect.info %></td>
        <td><%= link_to 'Show', proyect %></td>
        <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proyect.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @proyect.description %>
</p>

<p>
  <strong>Start:</strong>
  <%= @proyect.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @proyect.finish %>
</p>

<p>
  <strong>Status:</strong>
  <%= @proyect.info %>
</p>

<%= link_to 'Edit', edit_proyect_path(@proyect) %> |
<%= link_to 'Back', proyects_path %>